### run with :$ docker compose up
### from the login_server/db directory of corse

services:
  test_db_service:           # names the service
    image: postgres          # run the default postgres image from docker hub
    container_name: test_db  # names the container
    restart: always          # restart the container if it crashes
    environment:             # set environment variables
      POSTGRES_USER: madeup_default_user
      POSTGRES_PASSWORD: super_secret_password
      #POSTGRES_DB: test_db  # if you want to create a database right away
    
    ports:
      - "5011:5432"          # the port to expose port_on_your_computer:port_in_container