[package]
name = "login_server"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { version = "0.8.3", features = ["postgres", "runtime-tokio-rustls", "uuid"] }
tokio = { version = "1.44.2", features = ["full"] }
