[tasks.utils_test]
command = "cargo"
description = "run tests in utils module"
args = ["test", "--", "utils::tests::","--quiet"]
env = { "RUST_BACKTRACE" = "0" } # to prevent a long row of backtraces, remov eif your interested

[tasks.data_access_test]
command = "cargo"
description = "run tests in data_access module"
args = ["test", "--", "data_access::","--quiet"]
env = { "RUST_BACKTRACE" = "0" }

[tasks.crypt_test]
command = "cargo"
description = "run tests in crypt module"
args = ["test", "--", "crypt::tests::","--quiet"]
env = { "RUST_BACKTRACE" = "0" }

[tasks.integration_test]
command = "cargo"
description = "run integration tests"
args = ["test", "--", "integration_tests::","--quiet"]
env = { "RUST_BACKTRACE" = "0" }