[env]

# to only log from this crate
RUST_LOG = "login_server=debug" 

# DB
DB_CONNECTION_STRING = "postgres://postgres_user:super_secret_password@localhost:5011/test_db"
DB_DEFAULT_USER_CONNECTION_STRING = "postgres://madeup_default_user:super_secret_password@localhost:5011"

# jwt
JWT_KEY = "kL1sZs0d9yFjE9CnLq1B9PYLyD7fLzAHPYm5GwaJmQo="
JWT_TOKEN_DURRATION_SEC = "3000"